// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJy-JQylsreWUb4FMW-f0Iu481X2_JwU',
    appId: '1:298536464862:web:24066263215bc31e84ad4f',
    messagingSenderId: '298536464862',
    projectId: 'ppb-26',
    authDomain: 'ppb-26.firebaseapp.com',
    storageBucket: 'ppb-26.firebasestorage.app',
    measurementId: 'G-LJ5JV68NBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkX5gWtKEwwl-qFP8CMMEJtFkV5-uiaPY',
    appId: '1:298536464862:android:cc14bc8eeecee1f584ad4f',
    messagingSenderId: '298536464862',
    projectId: 'ppb-26',
    storageBucket: 'ppb-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZxMtc2eaxd4ZMFkTuBY9vGMwX3I0sho',
    appId: '1:298536464862:ios:a56c1b6ebadb408e84ad4f',
    messagingSenderId: '298536464862',
    projectId: 'ppb-26',
    storageBucket: 'ppb-26.firebasestorage.app',
    iosBundleId: 'com.example.stegoSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZxMtc2eaxd4ZMFkTuBY9vGMwX3I0sho',
    appId: '1:298536464862:ios:a56c1b6ebadb408e84ad4f',
    messagingSenderId: '298536464862',
    projectId: 'ppb-26',
    storageBucket: 'ppb-26.firebasestorage.app',
    iosBundleId: 'com.example.stegoSnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzJy-JQylsreWUb4FMW-f0Iu481X2_JwU',
    appId: '1:298536464862:web:ac6bb1e58ad4583684ad4f',
    messagingSenderId: '298536464862',
    projectId: 'ppb-26',
    authDomain: 'ppb-26.firebaseapp.com',
    storageBucket: 'ppb-26.firebasestorage.app',
    measurementId: 'G-GYQ7ZQ228F',
  );

}